version: '3.3'
services:
  jsenco: 
    container_name: jsenco
    build: .
    ports: 
      - "3333:3333"
    command: ["npm", "start"]
    volumes:
      - ./tests:/jsenco/tests
      - ./resultsData:/jsenco/results/data
    environment:
      PORT: 3333
networks:
  default:
    external:
      name: isolated_api